make compatible with python versions <3.9
using in python v3.8 gives following error message
```
nmq407@/projects/petar/fgf1/01_resolve$ python /projects/petar/fgf1/code/MindaGap/mindagap.py microscope_image.tiff 3 40 --edges False
Traceback (most recent call last):
  File "/projects/petar/fgf1/code/MindaGap/mindagap.py", line 110, in <module>
    parser.add_argument("-v", '--version', action=argparse.BooleanOptionalAction, default = False, help="Print version number.")
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
```

This is because `BooleanOptionalAction` class was added to the argparse module in Python 3.9. The behavior can be preserved and made compatible with older versions with the proposed change.